Create PR Fixes in Temp Directory
jfrog/frogbot pull request #112
Opened 2022-07-25 12:49 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.

---

2022-07-25 15:07 UTC, sverdlov93 commented on commands/utils/git.go
> +		Branch: getBranch(branchName),
```suggestion
		Branch: getFullBranchName(branchName),
```

2022-07-25 15:07 UTC, sverdlov93 commented on commands/utils/git.go
> +func getBranch(branchName string) plumbing.ReferenceName {
```suggestion
// Get full branch name ( for example: refs/heads/master)
func getFullBranchName(branchName string) plumbing.ReferenceName {
```

2022-07-25 15:07 UTC, sverdlov93 commented on commands/createfixpullrequests.go
> +		clientLog.Info("Start fixing", impactedPackage, "with", fixVersionInfo.fixVersion)
maybe add a log.info("------------...)
at the start of each loop

2022-07-26 11:44 UTC, eyalbe4 requested changes

2022-07-26 11:44 UTC, eyalbe4 commented on commands/utils/git.go
> +	// Gets the remote repo url from current .git dir
...from current .git dir... --> ...from the current .git dir...

2022-07-26 11:44 UTC, eyalbe4 commented on commands/utils/git.go
> +		return fmt.Errorf("'git remote %s' failed with error: %s", gm.remoteName, err.Error())
We will fail here due to nil pointer, if err is nil.

2022-07-26 11:44 UTC, eyalbe4 commented on commands/utils/git.go
> +	clientLog.Debug(fmt.Sprintf("project cloned from %s to %s", repoURL, destinationPath))
project --> Project

2022-07-26 11:44 UTC, eyalbe4 commented on commands/utils/git.go
> +		Username: "username", // The username can be anything except an empty string
Let's put the comment above the line is descrives.

... except an empty string --> ... except for an empty string

2022-07-26 11:44 UTC, eyalbe4 commented on commands/utils/git.go
> +// getFullBranchName returns the full branch name ( for example: refs/heads/master)
...( for example:... --> ...(for example:...

2022-07-26 11:44 UTC, eyalbe4 commented on commands/utils/git.go
> +// The input branchName can be short name (master) or full name (refs/heads/master)
...be short name (master) or full name... --> ...be a short name (master) or a full name..

2022-07-26 11:44 UTC, eyalbe4 commented on commands/createfixpullrequests.go
> +	// Cd to the temp working directory
...Cd to the temp... --> ...'CD' into the temp...

2022-07-26 13:11 UTC, merged