Suggest major versions changes
jfrog/frogbot pull request #300
Opened 2023-04-16 11:22 UTC by EyalDelarea

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
---

Return the ability to suggest major version changes (upgrade/downgrade) to fix an impacted package.
Also, change Frogbot badge to JFrog Frogbot.
And finally add extra test case for TestIsDirectDependency.

2023-04-16 15:05 UTC, eyalbe4 requested changes

2023-04-16 15:05 UTC, eyalbe4 commented on commands/createfixpullrequests.go
> +	for i := len(fixVersions) - 1; i >= 0; i-- {
I suggest we change the "fix version selection" algorithm to be the "closest version".

2023-04-17 13:26 UTC, omerzi commented on commands/utils/utils.go
> +// Accepts current impacted version and two of it's closest neighbours, upgrade and downgrade suggestions.
it's -> its

2023-04-17 13:26 UTC, omerzi commented on commands/utils/utils.go
> +		v1Part, _ := strconv.Atoi(v1Parts[i])
```suggestion
		v1Part, err := strconv.Atoi(v1Parts[i])
		if err != nil {
		     return "", err
		}
```

2023-04-17 13:43 UTC, omerzi requested changes
- Most of the logic under 'isVersionUpgrade', and `isVersionDowngrade` is similar. You can extract it into a general function that will receive a function based on the logic that differs between `isVersionUpgrade` and `isVersionDowngrade`.

- You can use the Version struct we defined in the gofrog package and modify it with these added functionalities. Keep it generic since gofrog is a generic Go package not related to Frogbot. 

- Errors should be returned. We don't want to ignore them most of the time.

2023-04-17 13:43 UTC, omerzi commented on commands/utils/utils.go
> +		v2Part, _ := strconv.Atoi(v2Parts[i])
```suggestion
		v2Part, err := strconv.Atoi(v2Parts[i])
		if err != nil {
		   return "", err
		}
```

2023-04-17 13:43 UTC, omerzi commented on commands/utils/utils.go
> +		v2Part, _ := strconv.Atoi(v2Parts[i])
return err on all usages of the `strconv.Atoi()`

2023-04-18 17:37 UTC, closed without merging