Add schedule event to GitLab and GitHub templates
jfrog/frogbot pull request #304
Opened 2023-04-18 11:59 UTC by omerzi

- [ ] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
---

2023-04-18 16:06 UTC, yahavi requested changes

2023-04-18 16:06 UTC, yahavi commented on docs/install-gitlab.md
> +    - if: $CI_PIPELINE_SOURCE == "schedule"
Looks repetition of push event.
Can we use "or"?
```yml
- if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule"
```

2023-04-18 16:06 UTC, yahavi commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
> +    # Creating fix pull requests will be triggered by any push to one of the these branches.q
```suggestion
    # Creating fix pull requests will be triggered by any push to one of these branches.
```

Let's remove the "the" in all other templates

2023-04-19 12:51 UTC, eyalbe4 requested changes

2023-04-19 12:51 UTC, eyalbe4 commented on docs/install-gitlab.md
> +      # For scheduled pipelines, creating fix pull requests will be triggered as well.
I suggest removing this line.

2023-04-19 12:51 UTC, eyalbe4 commented on docs/install-gitlab.md
>        # Creating fix pull requests will be triggered by any push to the default branch.
Creating fix pull requests will be triggered by any push to the default branch.
-->
Repository scanning is triggered by any push to the default branch.

2023-04-19 12:51 UTC, eyalbe4 commented on docs/install-gitlab.md
>        # You can change it to any other branch you want, for example:
You can change it to any other branch you want, for example:
-->
If you;d like a different branch to be scanned, replace $CI_DEFAULT_BRANCH in the line below with the name of branch, wrapped with quotes (").

2023-04-19 12:51 UTC, eyalbe4 commented on docs/install-gitlab.md
>        # if: $CI_COMMIT_BRANCH == "dev"
Let's remove this line.

2023-04-19 13:19 UTC, merged