Update workflows templates
jfrog/frogbot pull request #340
Opened 2023-05-17 13:37 UTC by EyalDelarea

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
---

Update workflows templates for create-fix-pull-requests for GitHub & GitLab.
Removing the push trigger and setting secluded job on specific branches.

2023-05-17 17:29 UTC, eyalbe4 requested changes

2023-05-17 17:29 UTC, eyalbe4 commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
> +        # Creating fix pull requests will be triggered periodically on the following branches.
Creating fix pull requests will be triggered periodically on the following branches.
-->
The repository scanning will be triggered periodically on the following branches.

(let's change in all templates).

2023-05-17 17:29 UTC, eyalbe4 commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
>      # The job will run once a day at 00:00 GMT.
The job will run once a day at 00:00 GMT.
-->
The repository will be scanned once a day at 00:00 GMT.

(let's change in all templates).

2023-05-18 08:25 UTC, sverdlov93 commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
> +          run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
```suggestion
          run: python -m pip install pipenv
```

2023-05-18 08:26 UTC, sverdlov93 commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
> +          run: pipx install poetry
```suggestion
          run: python -m pip install pipenv
```

2023-05-18 08:26 UTC, sverdlov93 commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
> +        - name: Setup Python
should be before poetry installl

2023-05-18 08:28 UTC, sverdlov93 commented on docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
> +        branch: [ "dev","main" ]
```suggestion
        branch: [ "dev", "main" ]
```

2023-05-18 08:29 UTC, sverdlov93 commented on starter-workflows/code-scanning/frogbot-scan-and-fix.yml
> +        branch: [ "dev","main" ]
```suggestion
        branch: [ "dev", "main" ]
```

2023-05-21 15:31 UTC, merged