Support workingDir and trim env
jfrog/frogbot pull request #38
Opened 2022-04-05 13:57 UTC by yahavi

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.

---

* Support new `JF_WORKING_DIR` environment variable to handle cases whereby the package descriptor is not in the root of the repository.
* Trim environment variables after reading them.

2022-04-06 06:53 UTC, talarian1 commented
I think we should consider adding a test project to this repo and an integration test for this scenario.

2022-04-06 06:53 UTC, talarian1 requested changes

2022-04-06 06:53 UTC, talarian1 commented on commands/scanpullrequest.go
> +	if params.WorkingDirectory != "" {
We should probably do the same in the `auditTarget` func.

2022-04-06 16:06 UTC, eyalbe4 requested changes

2022-04-06 16:06 UTC, eyalbe4 commented on templates/github-actions/frogbot-dotnet.yml
> +          # Relative path in the repository to the project
Relative path in the repository to the project
-->
Relative path to the project in the git repository 

Let's make this change in all templates.

2022-04-07 06:54 UTC, yahavi commented on commands/utils/params.go
> +func readParamFromEnv(envKey string, paramValue *string) error {
This logic returns an error:
```go
if *paramValue == "" {
	return &errMissingEnv{envKey}
}
```

2022-04-07 06:59 UTC, merged