Improve GitHub installation flow, remove all technology specific templates
jfrog/frogbot pull request #411
Opened 2023-08-03 17:31 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
---

2023-08-13 18:34 UTC, eyalbe4 requested changes
The `create-fix-pull-requests` phrase was left unreplaced in `install-github.md`.

2023-08-13 18:34 UTC, eyalbe4 commented on commands/utils/params.go
> +func NewRepoAggregator() RepoAggregator {
Looks like this function can be made private.

2023-08-13 18:34 UTC, eyalbe4 commented on commands/utils/params_test.go
> +// Pull request ID is not default, which mean we don't have branches related variables defined.
Wring grammar in this line.

2023-08-13 18:34 UTC, eyalbe4 commented on commands/utils/params_test.go
> +// Pull request ID is default 0, which mean we will have branches related variables.
Wring grammar in this line.

2023-08-15 14:57 UTC, EyalDelarea approved these changes
Reviewed the Jenkins Docs, looks amazing!

2023-08-15 17:03 UTC, merged