Add new usage reports
jfrog/frogbot pull request #426
Opened 2023-08-09 11:09 UTC by attiasas

- [ ] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
---

2023-08-20 09:20 UTC, yahavi requested changes

2023-08-20 09:20 UTC, yahavi commented on commands/utils/utils_test.go
> +	assert.Error(t, <-channel)
Let's use assert.ErrorContains to ensure the content of the error

2023-08-20 09:20 UTC, yahavi commented on commands/utils/utils_test.go
> +		channel <- ReportUsage("", &config.ServerDetails{ArtifactoryUrl: "http://httpbin.org/status/404"}, &usageGroup)
httpbin is not stable. We may get flaky tests.
Let's create a new usage handler that returns 404.

2023-08-20 09:20 UTC, yahavi commented on commands/utils/utils_test.go
> +		},
```suggestion
		Repository{Params: Params{Git: Git{RepoName: "repository1"}}},
		Repository{Params: Params{Git: Git{RepoName: "repository2"}}},
```

2023-08-20 09:20 UTC, yahavi commented on commands/utils/utils_test.go
> +func createUsageHandler(t *testing.T, commandName, clientId, clientId2 string) http.HandlerFunc {
This method became too long and not readable.
Let's create a usage handler for each server: createArtifactoryUsageHandler and createXrayUsageHandler.

2023-08-20 09:20 UTC, yahavi commented on commands/utils/utils_test.go
> +// Create HTTP handler to mock an Artifactory/Xray/Ecosystem server suitable for report usage requests
I couldn't find that it used for the Ecosystem server
```suggestion
// Create HTTP handler to mock an Artifactory/Xray server suitable for report usage requests
```

2023-08-21 06:28 UTC, eyalbe4 requested changes
I suggest encapsulating all the usage reporting code into a new UsageReporter struct, that can be initialized and executed. It also best to have this UsageReporter as part of jfrog-cli-core, so that we're able to utilize it in the future for JFrog CLI command as well, and not just for Frogbot.

2023-08-21 06:28 UTC, eyalbe4 commented on commands/utils/utils.go
> +func CreateEcosystemReports(commandName string, serverDetails *config.ServerDetails, repositories RepoAggregator) (reports []xrayusage.ReportEcosystemUsageData, err error) {
Can probably be made a private function.

2023-08-21 13:13 UTC, sverdlov93 commented on commands/utils/utils.go
> +			log.Debug("Ecosystem "+usage.ReportUsagePrefix, e.Error())
won't cause a double log?
on client and here?

2023-08-21 13:13 UTC, sverdlov93 commented on commands/utils/utils_test.go
>  		if r.RequestURI == "/api/system/version" {
can be converted to switch

2023-08-28 16:40 UTC, merged