New Frogobt sanity test
jfrog/frogbot pull request #49
Opened 2022-04-20 08:09 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.

---
This PR adds a new sanity test to the Frogbot tests suite. The new test will build and run the current code of Frogbot (including all the changes introduced by each PR).
Please notice, that the frogbot.yml is not changed and will trigger the most recent published Frogbot action when the "Frogbot scan" label is added.
The 2 comments can then be compared for sanity.

2022-04-25 06:40 UTC, yahavi requested changes

2022-04-25 06:40 UTC, yahavi commented on .github/workflows/test.yml
> +          JF_GIT_BASE_BRANCH: ${{ github.base_ref}}
```suggestion
          JF_GIT_BASE_BRANCH: ${{ github.base_ref }}
```

2022-04-25 06:40 UTC, yahavi commented on .github/workflows/test.yml
> +          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
I think we don't need these explanations in an internal sanity test
```suggestion
          JF_URL: ${{ secrets.FROGBOT_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2022-04-25 09:01 UTC, yahavi approved these changes

2022-04-25 09:07 UTC, merged

2022-05-24 12:12 UTC, sverdlov93 reviewed
LGTM