Fix Custom PR Title in Aggregated Mode
jfrog/frogbot pull request #496
Opened 2023-09-14 11:06 UTC by EyalDelarea

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
---

**Bug Description:**
When aggregate mode is on, custom template for the title wasn't loaded.

**Fix:**
Now custom templates will be loaded into aggregated PR title with tech suffix.
[Custom template] + "Go Dependencies".

2023-09-18 17:02 UTC, sverdlov93 commented on utils/git.go
> +	}
strings.join( techs, ",")

2023-09-19 07:57 UTC, omerzi requested changes

2023-09-19 07:57 UTC, omerzi commented on scanrepository/scanrepository.go
> +	projectTech []coreutils.Technology
A Project represents a technology with its working dirs, installCommand, etc. So this change is unnecessary.

2023-09-19 07:57 UTC, omerzi commented on utils/git.go
> +		// Aggregate commit message could not include each package, use PR title.
Unclear comment

2023-09-19 07:57 UTC, omerzi commented on utils/git.go
> +func removeMiddleSpaces(text string) string {
```suggestion
// Normalizes whitespace in text, ensuring that words are separated by a single space, and any extra whitespace is removed.
func normalizeWhitespaces(text string) string {
```

2023-09-19 07:57 UTC, omerzi commented on utils/git.go
> +	return strings.Join(strings.Fields(text), " ")
Add unit test

2023-09-19 07:57 UTC, omerzi commented on utils/git.go
> +func removeMiddleSpaces(text string) string {
+ move it to utils

2023-09-19 16:11 UTC, merged