Added "Back To top" button
jfrog/frogbot pull request #558
Opened 2023-10-25 16:09 UTC by PrajwalGraj

Added "Back To top" button in the bottom end of the Readme.md file.

- [ 👾] This pull request is on the dev branch.

---

2023-10-25 19:17 UTC, PrajwalGraj commented
I have read the CLA Document and I hereby sign the CLA


recheck

2023-10-28 16:13 UTC, PrajwalGraj commented
@omerzi Please review this PR

2023-10-28 17:44 UTC, eyalbe4 commented
@PrajwalGraj,
I believe your CLA signing comment is -
```
I have read the CLA Document and I hereby sign the CLA


recheck
```
instead of just being -
```
I have read the CLA Document and I hereby sign the CLA
```
Will you be able to try this?

2023-10-28 17:47 UTC, PrajwalGraj commented
I have read the CLA Document and I hereby sign the CLA

2023-10-28 17:48 UTC, eyalbe4 requested changes

2023-10-28 17:48 UTC, eyalbe4 commented on README.md
> +<p align="right">(<a href="#top">🔼 Back to top</a>)</p>
I think this link will look better without the enclosing parentheses.

2023-11-05 19:05 UTC, closed without merging