Enhance parsing of the maven-dep-tree output
jfrog/frogbot pull request #599
Opened 2023-12-06 08:45 UTC by omerzi

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
---
- Enhance parsing of the maven-dep-tree output ignoring the possible existence of a maven.config file.
- Regarding: https://github.com/jfrog/frogbot/issues/587#issuecomment-1838090462
- Based on: https://github.com/jfrog/jfrog-cli-core/pull/1062

2023-12-06 09:39 UTC, eyalbe4 requested changes

2023-12-06 09:39 UTC, eyalbe4 commented on utils/utils.go
> +// Returns a slice of these objects
Let's an example to this description, to help the reader quickly understand the functionality.

2023-12-06 09:40 UTC, eyalbe4 requested changes
Notice that some of the tests on this PR are failing.

2023-12-14 08:45 UTC, yahavi approved these changes

2023-12-14 09:04 UTC, merged