Add Support for Bitbucket Server
jfrog/frogbot pull request #67
Opened 2022-05-22 16:54 UTC by talarian1

- [] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.

---

2022-05-23 04:27 UTC, eyalbe4 requested changes
Let's think what the best strategy for testing this new functionality.

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +	// Send usage report
I suggested to @sverdlov93 in his PR to make changes to the `Send usage report` flow for all commands, so best to stay in sync with him about this.

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +// Scan pull requests by as follows:
...requests by as follows: --> ...requests as follows:

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +// b. Find the ones that should be scanned ( new pr or one with re-scan comment)
...( new pr or one with re-scan comment) --> ...(new PRs or PRs with a 're-scan' comment)

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +			//clean up
//clean up --> // Cleanup

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +			// download the pull request source ("from") branch
download --> Download

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +		// if found re-scan request
// if found re-scan request
-->
// If this a 're-scan' request comment

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +		// if found frogbot comment and not re-scan request, do not scan this pull request.
// if found frogbot comment and not re-scan request, do not scan this pull request.
-->
// if this is a Frogbot 'scan rsults' comment and not 're-scan' request comment, do not scan this pull request.

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +	// A new pull request - should be scanned
A new pull request - should be scanned
-->
This is a new pull request and it therefore should be scanned.

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +func isFrogbotComment(comment string) bool {
isFrogbotComment --> isFrogbotResultComment

2022-05-23 04:27 UTC, eyalbe4 commented on commands/scanpullrequests.go
> +func isReScanComment(comment string) bool {
isReScanComment --> isFrogbotRescanComment

2022-05-23 04:27 UTC, eyalbe4 commented on templates/Jenkins/Jenkinsfile
> +        // [Mandatory only for project which npm, pip, pipenv, nuget and dotnet]
[Mandatory only for project which npm, pip, pipenv, nuget and dotnet]
-->
[Mandatory only for projects which use npm, pip, pipenv, nuget and dotnet to download their dependencies]

This same error exists on the GitLab section in the README, so let's fix it there as well.

2022-05-23 16:12 UTC, sverdlov93 approved these changes

2022-05-23 16:24 UTC, merged

2022-05-24 12:12 UTC, sverdlov93 reviewed
LGTM