OIDC Integration
jfrog/frogbot pull request #694
Opened 2024-05-12 13:45 UTC by carmithersh

- [ ] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
- [ ] Update [documentation](https://github.com/jfrog/documentation) about new features / new supported technologies
---

2024-05-13 07:46 UTC, hadarshjfrog commented on action/src/utils.ts
> +    public static async validatePlatfornUrl(jfrogUrl: string): Promise<void> {
typo in "Platform"

2024-05-13 07:47 UTC, hadarshjfrog commented on action/lib/utils.js
> +Utils.OIDC_INTEGRATION_PROVIDER_NAME = 'oidc-provider-name';
I suggest being consistent with the naming convention - if it's an argument name - so both the OIDC args should end with _ARG

2024-05-13 07:49 UTC, hadarshjfrog commented on action/src/utils.ts
> +    private static readonly OIDC_INTEGRATION_PROVIDER_NAME: string = 'oidc-provider-name';
I suggest being consistent with the naming convention - if it's an argument name - so both the OIDC args should end with _ARG

2024-05-13 07:51 UTC, hadarshjfrog commented on action/src/main.ts
> +        if (!jfrogUrl) {
obviously can be in both - but if the following function is validatePlatformUrl - shouldn't we validate it there?

2024-05-13 07:56 UTC, hadarshjfrog commented
Please add a oidc-test action, similar to the existing one in the cli

2024-05-13 09:55 UTC, yahavi requested changes
Well done, @carmithersh!
Please consider my inline comments.

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +
```suggestion
```

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +        }catch (error: any) {
Please make sure to run `npm run format` to ensure no formatting issues
```suggestion
        } catch (error: any) {
```

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +        }
This code can be arrange and simplified:
```suggestion
        if (response.message.statusCode == 200) {
            const body: string = await response.readBody();
            if (body == 'OK') {
                return;
            }
        }
        throw new Error(jfrogUrlFailure);
```

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +
Redundant new line
```suggestion
```

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +    public static async getJfrogOIDCCredentials(jfrogUrl: string): Promise<void> {
The function's name doesn't really match what it does - It doesn't return OIDC credentials from JFrog (the return value is void).

This function retrieves a JWT from GitHub and forwards it to the JFrog platform to obtain a valid access token. This process occurs only if the user hasn't supplied the `oidc-provider-name` argument.
I'd call it `setupOIDCTokenIfNeeded`.

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +            // no token is set if no oidc provider was configured
```suggestion
            // No token is set if no OIDC provider was configured
```

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +        // If we've reached this stage, the jfrogCredentials.jfrogUrl field should hold a non-empty value obtained from process.env.JF_URL
This explanation should be as JSDoc above this function. 
See, as a reference, the documentation of cacheAndAddPath.

2024-05-13 09:55 UTC, yahavi commented on action/src/utils.ts
> +        return ;
```suggestion
```

2024-05-13 09:58 UTC, yahavi commented on package-lock.json
This file should be deleted

2024-05-13 09:58 UTC, yahavi commented on testdata/projects/gradle/.gradle/7.6/checksums/checksums.lock
Please delete all of this directory

2024-05-15 05:41 UTC, carmithersh commented on .gitignore
> -*mock*
its required for the http client dependency, for an inner library.

2024-05-15 06:41 UTC, eranturgeman commented on .gitignore
> -*mock*
is there any way to overpass it?
What is the required dependency that you need to push mocks for?

2024-05-15 06:59 UTC, eranturgeman commented on .github/workflows/action-test.yml
> +run-name: ${{ github.actor }} is testing OIDC-Access integration
```suggestion

```

Why do we need this?
This CI file is not intended to test the OIDC flow only.

2024-05-15 08:10 UTC, carmithersh commented on .gitignore
> -*mock*
@action/httpclient requires undici which requires mock 
so, please add an .gitignore to all the mock files you wish excluded from git

2024-05-15 10:27 UTC, eranturgeman commented on action/action.yml
> +  color: "green"
```suggestion

```
This file is a duplication to action.yml that is found in the root.

2024-05-15 10:33 UTC, eranturgeman commented on action/src/main.ts
> +
```suggestion
```

2024-05-15 10:38 UTC, eranturgeman commented on action/src/utils.ts
> +        const jfrogUrlFailure: string = 'JF_URL must point on your full platform URL, for example: https://mycompany.jfrog.io/, make sure the platform is up and running and accessible.'
If possible please define this const error message outside the function and the top of the file

2024-05-15 10:40 UTC, eranturgeman commented on action/src/utils.ts
> +        //verify that the provided JFrog URL is valid and responsive
```suggestion
        // Verify that the provided JFrog URL is valid and responsive
```

2024-05-15 10:45 UTC, eranturgeman commented on action/src/utils.ts
> +        // assuming in this method that add parameters were provided
```suggestion
        // Assuming in this method that add parameters were provided
```
Also, what is "add parameters"?

2024-05-15 10:49 UTC, eranturgeman commented on testdata/projects/gradle/.gradle/buildOutputCleanup/cache.properties
> +gradle.version=7.6
what are those files that were added in testdata/projectsgradle/.gradle dir?
I didn't see where you use a gradle project in this PR. Please just make sure those files were not added by mistake

2024-05-15 12:49 UTC, eranturgeman commented on action/src/main.ts
> +        //validate JF_URL
```suggestion
        // Validate JF_URL
```

2024-05-19 07:47 UTC, closed without merging