Add Tests for shouldScanPullRequest logic
jfrog/frogbot pull request #76
Opened 2022-05-24 16:13 UTC by talarian1

- [ ] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.

---

2022-05-24 16:35 UTC, sverdlov93 approved these changes

2022-05-29 08:27 UTC, yahavi requested changes
Looks good! 🏅

2022-05-29 08:27 UTC, yahavi commented on commands/utils/icons_test.go
> +
```suggestion
```

2022-05-29 08:27 UTC, yahavi commented on commands/testdata/vcsclientmock.go
> +// Code generated by MockGen. DO NOT EDIT.
This file is autogenerated and therefore I suggest not adding it to the repository.

2022-05-29 08:37 UTC, merged