Added Frogbot support for viewing all of the vulnerabilities + Updated Frogbot images
jfrog/frogbot pull request #98
Opened 2022-06-27 11:58 UTC by omerzi

- [x] All [tests](https://github.com/jfrog/frogbot#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.

---
Fixes issue #96 
- The 'JF_INCLUDE_ALL_SCAN' environment variable now allows Frogbot to display all existing vulnerabilities, not just the new ones. 
- The Frogbot images have been updated.

2022-07-03 15:13 UTC, talarian1 requested changes

2022-07-03 15:13 UTC, talarian1 commented on go.sum
> +golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9/go.mod h1:LzIPMQfyMNhhGPhUkYOs5KpL4U8rLKemX1yGLhDgUto=
Unnecessary change to go.sum
You may run `go mod tidy` before committing changes to go.mod & go.sum.

2022-07-04 08:36 UTC, omerzi commented on commands/utils/params.go
> +	IncludeAllScan     string
It represent an environment variable, so we need to get it as a string anyway, what do you think?

2022-07-04 08:36 UTC, omerzi commented on commands/scanpullrequest.go
>  	return vulnerabilitiesRows
done

2022-07-04 09:09 UTC, talarian1 requested changes

2022-07-04 09:09 UTC, talarian1 commented on commands/scanpullrequest.go
> +	if params.IncludeAllVulnerabilities == true {
```suggestion
	if params.IncludeAllVulnerabilities {
```

2022-07-04 09:09 UTC, talarian1 commented on commands/utils/params.go
> +		params.IncludeAllVulnerabilities = false
Let's log the error, so customers can understand what went wrong with the value of this flag.

2022-07-04 11:16 UTC, talarian1 approved these changes

2022-07-04 12:23 UTC, merged